name: baap_communication_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  http: ^1.2.1
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.1
  go_router: ^14.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  image_picker: ^1.1.1
  mime: ^1.0.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/env/
    - assets/images/
    - assets/icons/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
